"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ


BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent

env = environ.Env(
    APP_DEBUG=(bool, False),
)

environ.Env.read_env(ROOT_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("APP_DEBUG", default=False)

# Le serveur Django de développement peut servir les photos locales sans
# activer DEBUG. Ce réglage reste désactivé par défaut et doit être demandé
# explicitement dans l'environnement local.
SERVE_MEDIA_LOCALLY = env.bool(
    "SERVE_MEDIA_LOCALLY",
    default=False,
)

ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"],
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "daphne",
    "django.contrib.staticfiles",

    "channels",
    "rest_framework",

    "apps.accounts.apps.AccountsConfig",
    "apps.core.apps.CoreConfig",
    "apps.profiles.apps.ProfilesConfig",
    "apps.interactions.apps.InteractionsConfig",
    "apps.safety.apps.SafetyConfig",
    "apps.photos.apps.PhotosConfig",
    "apps.messaging.apps.MessagingConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.subscriptions.apps.SubscriptionsConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ce dossier contient les surcharges visuelles de l'administration
        # Mbolo. Les templates des applications restent également disponibles
        # grâce à APP_DIRS=True.
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST", default="127.0.0.1"),
        "PORT": env.int(
            "POSTGRES_PORT",
            default=env.int("POSTGRES_EXPOSED_PORT", default=5432),
        ),
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "connect_timeout": 5,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_RESET_TIMEOUT = env.int(
    "PASSWORD_RESET_TIMEOUT",
    default=1800,
)


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Le slash initial rend l'URL absolue. Sans lui, une page comme
# /admin/profiles/... chercherait parfois ses styles dans une mauvaise route.
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

# ============================================================
# SÉCURITÉ HTTP, COOKIES ET DÉPLOIEMENT
# ============================================================

# Les hôtes et origines autorisés viennent exclusivement de l'environnement.
# Cela évite qu'une valeur locale codée en dur écrase la configuration de
# production.
ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"],
)

CSRF_TRUSTED_ORIGINS = env.list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
)

# Le domaine frontal utilisé dans les e-mails et redirections.
FRONTEND_BASE_URL = env(
    "FRONTEND_BASE_URL",
    default="http://localhost:5173",
).rstrip("/")

# En production derrière Nginx, Traefik ou un load balancer TLS, Django doit
# pouvoir reconnaître la requête HTTPS transmise par le proxy.
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if env.bool("DJANGO_TRUST_X_FORWARDED_PROTO", default=False)
    else None
)

USE_HTTPS_SECURITY = env.bool(
    "DJANGO_USE_HTTPS_SECURITY",
    default=not DEBUG,
)

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = USE_HTTPS_SECURITY

# Le cookie CSRF doit rester lisible par le frontend afin qu'Axios puisse
# envoyer l'en-tête X-CSRFToken. Il ne contient pas la session utilisateur.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = USE_HTTPS_SECURITY

SECURE_SSL_REDIRECT = env.bool(
    "DJANGO_SECURE_SSL_REDIRECT",
    default=USE_HTTPS_SECURITY,
)
SECURE_HSTS_SECONDS = env.int(
    "DJANGO_SECURE_HSTS_SECONDS",
    default=31536000 if USE_HTTPS_SECURITY else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=USE_HTTPS_SECURITY,
)
SECURE_HSTS_PRELOAD = env.bool(
    "DJANGO_SECURE_HSTS_PRELOAD",
    default=False,
)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

# Réduit l'exposition des pages sensibles dans les navigateurs et proxys.
SESSION_SAVE_EVERY_REQUEST = False

# ==========================================================
# CACHE REDIS
# ==========================================================

REDIS_HOST = env("REDIS_HOST", default="127.0.0.1")
REDIS_PORT = env.int(
    "REDIS_PORT",
    default=env.int("REDIS_EXPOSED_PORT", default=6379),
)

REDIS_CACHE_URL = (
    f"redis://:{env('REDIS_PASSWORD')}"
    f"@{REDIS_HOST}:{REDIS_PORT}/1"
)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "TIMEOUT": 300,
        "KEY_PREFIX": "mbolo",
        "OPTIONS": {
            "socket_connect_timeout": 3,
            "socket_timeout": 3,
        },
    }
}


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.accounts.authentication.ActiveAccountSessionAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}



# ==========================================================
# E-MAILS DE DÉVELOPPEMENT
# ==========================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)

DEFAULT_FROM_EMAIL = "Mbolo <no-reply@mbolo.local>"


# ============================================================
# FICHIERS MÉDIAS ET PHOTOS DE PROFIL
# ============================================================

# URL publique utilisée pendant le développement local.
#
# En production, les médias seront servis par un stockage dédié,
# un CDN ou un proxy web sécurisé, et non directement par Django.
MEDIA_URL = "/media/"

# Dossier physique de stockage pendant le développement.
MEDIA_ROOT = BASE_DIR / "media"

# Les selfies de vérification sont des justificatifs privés.
# Ils sont donc stockés hors de MEDIA_ROOT et ne peuvent jamais être
# servis par la route publique /media/ utilisée pour les photos de profil.
PRIVATE_VERIFICATION_MEDIA_ROOT = (
    BASE_DIR / "private_media" / "profile_verifications"
)


# ============================================================
# LIMITES DE TÉLÉVERSEMENT
# ============================================================

# Taille maximale du corps global d'une requête multipart.
#
# La valeur est légèrement supérieure à la limite de l'image
# afin de conserver de la place pour les en-têtes multipart.
DATA_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024

# Taille maximale avant que Django utilise un fichier temporaire
# plutôt que de conserver entièrement l'upload en mémoire.
FILE_UPLOAD_MAX_MEMORY_SIZE = 8 * 1024 * 1024


# ============================================================
# POLITIQUE DE SÉCURITÉ DES PHOTOS
# ============================================================

# Six photos maximum par profil.
PROFILE_PHOTO_MAX_COUNT = 6

# Taille maximale du fichier original : 8 Mio.
PROFILE_PHOTO_MAX_BYTES = 8 * 1024 * 1024

# Dimensions minimales.
#
# Une image trop petite devient floue après recadrage.
PROFILE_PHOTO_MIN_WIDTH = 320
PROFILE_PHOTO_MIN_HEIGHT = 320

# Dimensions maximales acceptées avant réencodage.
#
# Cette limite contribue à réduire les risques liés
# aux bombes de décompression et à la consommation mémoire.
PROFILE_PHOTO_MAX_WIDTH = 6000
PROFILE_PHOTO_MAX_HEIGHT = 6000

# Dimensions du fichier final réencodé.
PROFILE_PHOTO_OUTPUT_MAX_WIDTH = 1600
PROFILE_PHOTO_OUTPUT_MAX_HEIGHT = 1600

# Qualité WebP du fichier final.
PROFILE_PHOTO_WEBP_QUALITY = 88


# ==========================================================
# DJANGO CHANNELS / WEBSOCKET
# ==========================================================
#
# Redis DB 1 reste réservé au cache Django.
# Redis DB 2 est réservé au Channel Layer afin de séparer
# les clés de cache des messages internes de Channels.
#
REDIS_CHANNEL_URL = (
    f"redis://:{env('REDIS_PASSWORD')}"
    f"@{REDIS_HOST}:{REDIS_PORT}/2"
)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_CHANNEL_URL],
            "capacity": 1000,
            "expiry": 60,
            "group_expiry": 86400,
        },
    },
}
# Les comptes gratuits disposent d'un quota journalier calculé et
# contrôlé exclusivement par Django. Les abonnements actifs possédant
# l'entitlement unlimited_likes ne sont pas concernés.
MBOLO_FREE_DAILY_LIKE_LIMIT = env.int(
    "MBOLO_FREE_DAILY_LIKE_LIMIT",
    default=20,
)


# ============================================================
# MBOLO PREMIUM ET PAIEMENTS
# ============================================================
#
# Le mode test doit être explicitement activé. En production, son activation
# accidentelle provoque une erreur immédiate au démarrage.
#
MBOLO_PLUS_PRICE_XAF = env.int("MBOLO_PLUS_PRICE_XAF", default=5000)
MBOLO_PRESTIGE_PRICE_XAF = env.int(
    "MBOLO_PRESTIGE_PRICE_XAF",
    default=10000,
)
MBOLO_PAYMENT_PROVIDER = env(
    "MBOLO_PAYMENT_PROVIDER",
    default="mbolo_test" if DEBUG else "",
).strip()
MBOLO_PAYMENT_TEST_MODE = env.bool(
    "MBOLO_PAYMENT_TEST_MODE",
    default=DEBUG,
)

if not DEBUG and MBOLO_PAYMENT_TEST_MODE:
    raise RuntimeError(
        "MBOLO_PAYMENT_TEST_MODE ne peut pas être activé lorsque APP_DEBUG=false."
    )

if not MBOLO_PAYMENT_TEST_MODE and not MBOLO_PAYMENT_PROVIDER:
    raise RuntimeError(
        "MBOLO_PAYMENT_PROVIDER doit être défini lorsque le mode test est désactivé."
    )
