"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ


BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent

env = environ.Env(
    APP_DEBUG=(bool, False),
)

environ.Env.read_env(ROOT_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("APP_DEBUG", default=False)

ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"],
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "daphne",
    "django.contrib.staticfiles",

    "channels",
    "rest_framework",

    "apps.accounts.apps.AccountsConfig",
    "apps.core.apps.CoreConfig",
    "apps.profiles.apps.ProfilesConfig",
    "apps.interactions.apps.InteractionsConfig",
    "apps.safety.apps.SafetyConfig",
    "apps.photos.apps.PhotosConfig",
    "apps.messaging.apps.MessagingConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": "127.0.0.1",
        "PORT": env.int("POSTGRES_EXPOSED_PORT", default=5432),
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "connect_timeout": 5,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

# ============================================================
# HÔTES HTTP AUTORISÉS
# ============================================================
#
# Django vérifie l'en-tête HTTP Host afin d'empêcher certaines
# attaques utilisant un nom d'hôte falsifié.
#
# En développement local, nous autorisons uniquement :
#
# - 127.0.0.1 ;
# - localhost.
#
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]


# ============================================================
# ORIGINES CSRF AUTORISÉES
# ============================================================
#
# Le frontend React/Vite fonctionne actuellement sur le port 5173.
#
# Le navigateur peut utiliser :
#
# - http://127.0.0.1:5173 ;
# - http://localhost:5173.
#
# Ces origines sont explicitement autorisées pour les requêtes
# protégées par CSRF :
#
# - POST ;
# - PUT ;
# - PATCH ;
# - DELETE.
#
# Nous n'utilisons jamais "*" ici, car cela affaiblirait
# la vérification de l'origine.
#
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

# ==========================================================
# CACHE REDIS
# ==========================================================

REDIS_CACHE_URL = (
    f"redis://:{env('REDIS_PASSWORD')}"
    f"@127.0.0.1:"
    f"{env.int('REDIS_EXPOSED_PORT', default=6379)}"
    "/1"
)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "TIMEOUT": 300,
        "KEY_PREFIX": "mbolo",
        "OPTIONS": {
            "socket_connect_timeout": 3,
            "socket_timeout": 3,
        },
    }
}


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}



# ==========================================================
# E-MAILS DE DÉVELOPPEMENT
# ==========================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)

DEFAULT_FROM_EMAIL = "Mbolo <no-reply@mbolo.local>"

FRONTEND_BASE_URL = env(
    "FRONTEND_BASE_URL",
    default="http://localhost:5173",
)





# ============================================================
# FICHIERS MÉDIAS ET PHOTOS DE PROFIL
# ============================================================

# URL publique utilisée pendant le développement local.
#
# En production, les médias seront servis par un stockage dédié,
# un CDN ou un proxy web sécurisé, et non directement par Django.
MEDIA_URL = "/media/"

# Dossier physique de stockage pendant le développement.
MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# LIMITES DE TÉLÉVERSEMENT
# ============================================================

# Taille maximale du corps global d'une requête multipart.
#
# La valeur est légèrement supérieure à la limite de l'image
# afin de conserver de la place pour les en-têtes multipart.
DATA_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024

# Taille maximale avant que Django utilise un fichier temporaire
# plutôt que de conserver entièrement l'upload en mémoire.
FILE_UPLOAD_MAX_MEMORY_SIZE = 8 * 1024 * 1024


# ============================================================
# POLITIQUE DE SÉCURITÉ DES PHOTOS
# ============================================================

# Six photos maximum par profil.
PROFILE_PHOTO_MAX_COUNT = 6

# Taille maximale du fichier original : 8 Mio.
PROFILE_PHOTO_MAX_BYTES = 8 * 1024 * 1024

# Dimensions minimales.
#
# Une image trop petite devient floue après recadrage.
PROFILE_PHOTO_MIN_WIDTH = 320
PROFILE_PHOTO_MIN_HEIGHT = 320

# Dimensions maximales acceptées avant réencodage.
#
# Cette limite contribue à réduire les risques liés
# aux bombes de décompression et à la consommation mémoire.
PROFILE_PHOTO_MAX_WIDTH = 6000
PROFILE_PHOTO_MAX_HEIGHT = 6000

# Dimensions du fichier final réencodé.
PROFILE_PHOTO_OUTPUT_MAX_WIDTH = 1600
PROFILE_PHOTO_OUTPUT_MAX_HEIGHT = 1600

# Qualité WebP du fichier final.
PROFILE_PHOTO_WEBP_QUALITY = 88


# ==========================================================
# DJANGO CHANNELS / WEBSOCKET
# ==========================================================
#
# Redis DB 1 reste réservé au cache Django.
# Redis DB 2 est réservé au Channel Layer afin de séparer
# les clés de cache des messages internes de Channels.
#
REDIS_CHANNEL_URL = (
    f"redis://:{env('REDIS_PASSWORD')}"
    f"@127.0.0.1:"
    f"{env.int('REDIS_EXPOSED_PORT', default=6379)}"
    "/2"
)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_CHANNEL_URL],
            "capacity": 1000,
            "expiry": 60,
            "group_expiry": 86400,
        },
    },
}
