# Generated by Django 5.2.16 on 2026-07-18 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_blocks', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_block',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='block_blocker_created_idx'), models.Index(fields=['blocked_user', '-created_at'], name='block_blocked_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked_user'), name='uniq_blocker_blocked_user'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked_user')), _negated=True), name='block_users_must_differ')],
            },
        ),
    ]
