# Generated by Django 5.2.16 on 2026-07-18 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('harassment', 'Harcèlement'), ('fake_profile', 'Faux profil ou usurpation'), ('scam', 'Arnaque ou sollicitation financière'), ('inappropriate_content', 'Contenu inapproprié'), ('threat', 'Menace ou violence'), ('spam', 'Spam ou sollicitation abusive'), ('underage_suspicion', 'Suspicion de personne mineure'), ('other', 'Autre motif')], max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', "En cours d'examen"), ('resolved', 'Traité'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=24)),
                ('moderator_note', models.TextField(blank=True, default='', max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_report',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['reporter', '-created_at'], name='report_reporter_created_idx'), models.Index(fields=['reported_user', '-created_at'], name='report_target_created_idx'), models.Index(fields=['status', '-created_at'], name='report_status_created_idx'), models.Index(fields=['reason', '-created_at'], name='report_reason_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reporter', models.F('reported_user')), _negated=True), name='report_users_must_differ')],
            },
        ),
    ]
