# Generated by Django 5.2.16 on 2026-07-18 07:02

import apps.profiles.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True, validators=[apps.profiles.models.validate_adult_birth_date])),
                ('gender', models.CharField(blank=True, choices=[('man', 'Homme'), ('woman', 'Femme'), ('non_binary', 'Non binaire'), ('prefer_not_to_say', 'Préfère ne pas préciser')], default='', max_length=32)),
                ('city', models.CharField(blank=True, choices=[('libreville', 'Libreville'), ('port_gentil', 'Port-Gentil'), ('franceville', 'Franceville'), ('oyem', 'Oyem'), ('moanda', 'Moanda'), ('lambarene', 'Lambaréné'), ('mouila', 'Mouila'), ('tchibanga', 'Tchibanga'), ('koulamoutou', 'Koulamoutou'), ('makokou', 'Makokou'), ('bitam', 'Bitam'), ('other', 'Autre ville')], default='', max_length=32)),
                ('biography', models.TextField(blank=True, default='', max_length=500)),
                ('dating_intent', models.CharField(blank=True, choices=[('serious_relationship', 'Relation sérieuse'), ('friendship', 'Amitié'), ('discussion', 'Discussion'), ('marriage', 'Mariage'), ('not_sure', 'Je ne sais pas encore')], default='', max_length=32)),
                ('is_discoverable', models.BooleanField(default=False, help_text="Autorise l'apparition du profil dans les résultats de découverte.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_profile',
                'ordering': ('-created_at',),
            },
        ),
    ]
