# Generated by Django 5.2.16 on 2026-07-18 07:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_discoverable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SearchPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_age', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('maximum_age', models.PositiveSmallIntegerField(default=45, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('preferred_genders', models.JSONField(blank=True, default=list)),
                ('preferred_cities', models.JSONField(blank=True, default=list)),
                ('preferred_dating_intents', models.JSONField(blank=True, default=list)),
                ('maximum_distance_km', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('only_verified_profiles', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences de recherche',
                'verbose_name_plural': 'Préférences de recherche',
                'db_table': 'profiles_search_preferences',
                'ordering': ('-created_at',),
            },
        ),
    ]
