from django.urls import path

from .security_alert_preferences import (
    LoginAlertEmailPreferenceView,
)
from .views import (
    ActivityHeartbeatView,
    ChangePasswordView,
    CurrentUserView,
    EmailVerificationConfirmView,
    EmailVerificationRequestView,
    EmailTwoFactorConfirmView,
    EmailTwoFactorSettingsView,
    DeactivateAccountView,
    LoginView,
    LoginActivityListView,
    LogoutView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PermanentAccountDeleteView,
    PersonalDataExportView,
    RevokeOtherSessionsView,
    RegisterView,
)


app_name = "accounts"

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path(
        "login/2fa/confirm/",
        EmailTwoFactorConfirmView.as_view(),
        name="login-2fa-confirm",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "activity/",
        ActivityHeartbeatView.as_view(),
        name="activity-heartbeat",
    ),
    path(
        "security/login-activity/",
        LoginActivityListView.as_view(),
        name="login-activity",
    ),
    path(
        "security/login-alert-emails/",
        LoginAlertEmailPreferenceView.as_view(),
        name="login-alert-email-preference",
    ),
    path(
        "me/",
        CurrentUserView.as_view(),
        name="current-user",
    ),
    path(
        "email-verification/request/",
        EmailVerificationRequestView.as_view(),
        name="email-verification-request",
    ),
    path(
        "email-verification/confirm/",
        EmailVerificationConfirmView.as_view(),
        name="email-verification-confirm",
    ),
    path(
        "password-reset/request/",
        PasswordResetRequestView.as_view(),
        name="password-reset-request",
    ),
    path(
        "password-reset/confirm/",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "security/change-password/",
        ChangePasswordView.as_view(),
        name="change-password",
    ),
    path(
        "security/revoke-sessions/",
        RevokeOtherSessionsView.as_view(),
        name="revoke-other-sessions",
    ),
    path(
        "security/email-2fa/",
        EmailTwoFactorSettingsView.as_view(),
        name="email-2fa-settings",
    ),
    path(
        "security/deactivate/",
        DeactivateAccountView.as_view(),
        name="deactivate-account",
    ),
    path(
        "privacy/export/",
        PersonalDataExportView.as_view(),
        name="personal-data-export",
    ),
    path(
        "privacy/delete/",
        PermanentAccountDeleteView.as_view(),
        name="permanent-account-delete",
    ),
]
