# Generated by Django 5.2.16 on 2026-07-18 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_profile_is_discoverable_searchpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('like', "J'aime"), ('pass', 'Passer')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interactions', to=settings.AUTH_USER_MODEL)),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to='profiles.profile')),
            ],
            options={
                'db_table': 'interactions_interaction',
                'ordering': ('-updated_at', '-created_at'),
                'indexes': [models.Index(fields=['actor', 'decision', '-updated_at'], name='inter_actor_decision_idx'), models.Index(fields=['target_profile', 'decision'], name='inter_target_decision_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor', 'target_profile'), name='uniq_actor_target_inter')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile_one', to='profiles.profile')),
                ('profile_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile_two', to='profiles.profile')),
            ],
            options={
                'db_table': 'interactions_match',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['profile_one', 'is_active', '-created_at'], name='match_prof1_active_idx'), models.Index(fields=['profile_two', 'is_active', '-created_at'], name='match_prof2_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile_one', 'profile_two'), name='uniq_profile_pair_match'), models.CheckConstraint(condition=models.Q(('profile_one', models.F('profile_two')), _negated=True), name='match_profiles_different')],
            },
        ),
    ]
