# Generated by Django 5.2.16 on 2026-07-18 10:32

import apps.photos.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_profile_is_discoverable_searchpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, upload_to=apps.photos.models.profile_photo_upload_path)),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'db_table': 'photos_profile_photo',
                'ordering': ('position', 'created_at'),
                'indexes': [models.Index(fields=['profile', 'position'], name='photo_profile_position_idx'), models.Index(fields=['profile', 'is_primary'], name='photo_profile_primary_idx'), models.Index(fields=['profile', '-created_at'], name='photo_profile_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'position'), name='photo_profile_position_uniq'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('profile',), name='photo_one_primary_profile')],
            },
        ),
    ]
